# Generated by Django 4.1.3 on 2022-11-14 08:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_product_purchase_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
