# Generated by Django 4.1.3 on 2022-11-15 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0004_alter_purchase_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
