# Generated by Django 4.1.3 on 2022-11-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0005_alter_return_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
