# Generated by Django 4.1.3 on 2022-11-17 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0006_alter_return_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
