# Generated by Django 4.1.3 on 2022-11-22 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0007_alter_return_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='delete_id',
        ),
        migrations.AddField(
            model_name='return',
            name='delete',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='myshop.purchase'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='return',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
