# Generated by Django 4.1.3 on 2022-11-22 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0008_remove_return_delete_id_return_delete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='delete',
        ),
        migrations.AddField(
            model_name='return',
            name='purchase',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='myshop.purchase'),
            preserve_default=False,
        ),
    ]
