# Generated by Django 4.1.3 on 2022-11-22 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0009_remove_return_delete_return_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='return',
            old_name='purchase',
            new_name='delete',
        ),
    ]
