# Generated by Django 4.1.3 on 2022-11-22 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0010_rename_purchase_return_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='return',
            old_name='delete',
            new_name='delete_id',
        ),
    ]
