# Generated by Django 4.1.3 on 2022-11-22 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0011_rename_delete_return_delete_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
