# Generated by Django 4.1.3 on 2022-11-22 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0012_alter_return_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='delete_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshop.purchase'),
        ),
    ]
