# Generated by Django 4.1.3 on 2022-11-23 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0013_alter_return_delete_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='delete_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myshop.purchase'),
        ),
    ]
