# Generated by Django 4.1.3 on 2022-11-23 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0014_alter_return_delete_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='return',
            old_name='delete_id',
            new_name='purchase',
        ),
    ]
