# Generated by Django 4.1.3 on 2022-11-23 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0015_rename_delete_id_return_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='return',
            old_name='purchase',
            new_name='delete_id',
        ),
    ]
